# vboxmanage list vms
# vagrant package --base vagrant_master_* --output master.box

# Configure boxes
Vagrant.configure('2') do |config|
  config.vm.box = 'bento/centos-7.4'
  #config.ssh.insert_key = false

  config.vm.define 'chef-server' do |cs|
    cs.vm.network 'private_network', ip: '192.168.123.10'
    cs.vm.hostname = 'chef-server'
    
    cs.vm.provision 'shell', path: 'keys.sh'
    cs.vm.provision 'shell', path: 'chef-server.sh'
  end
  
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.network 'private_network', ip: "192.168.123.1#{i}"
      node.vm.hostname = "node#{i}"

      node.vm.provider 'virtualbox' do |vb|
        vb.memory = '512'
      end

      node.vm.provision 'shell', path: 'keys.sh'
      node.vm.provision 'shell', path: 'node.sh'
    end
  end
end
